export default [
    { value: "MATH", name: "Mathematique" },
    { value: "INF", name: "Informatique" },
    { value: "BIOS", name: "BioScience" },
    { value: "PHYS", name: "Physique" },
    { value: "CHIM", name: "Chimie" },
    { value: "ICT4D", name: "ICT4D" },
    { value: "SIGL", name: "SIGL" },
    { value: "RAM", name: "RAM" },
    { value: "SSI", name: "SSI" },
    { value: "MED", name: "MED" },
    { value: "PHARM", name: "PHARM" },
    { value: "ODON", name: "ODON" },
    { value: "SOCIO", name: "SOCIO" },
    { value: "ANTHRO", name: "ANTHRO" },
    { value: "PSYCHO", name: "PSYCHO" },
    { value: "LLF", name: "LLF" },
    { value: "LLA", name: "LLA" },
    { value: "LLR", name: "LLR" },
    { value: "HIST", name: "HIST" },
    { value: "RT", name: "RT" },
    { value: "RC", name: "RC" },
    { value: "IR", name: "IR" },
    { value: "AUTRE", name: "AUTRE" },
  ];